[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dsclinic"
version = "2.1.4"
description = "DSClinic AI - Alat za analizu medicinskih izveštaja (Laboratorija i NLS)"
dependencies = [
    "google-genai",
    "pydantic"
]

[tool.setuptools.packages.find]
where = ["src"]

[autopep8]
max_line_length = 500


